import React, { useState } from 'react';
import { Terminal, Cpu, Play, CheckCircle2, Clock, UserCheck, Shield, ChevronDown, ChevronRight, Layers, FileCode } from 'lucide-react';

export const McpProcessPage = ({ logs }) => {
  const [expandedLogId, setExpandedLogId] = useState(logs[0]?.id || null);

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="p-6 rounded-3xl bg-slate-900/80 border border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-purple-400 text-xs font-mono font-medium mb-1">
            <Cpu className="h-4 w-4" /> Multi-User Process Auditor
          </div>
          <h2 className="text-xl font-bold text-white">
            MCP Server Execution & Tool Logs
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Audit tool calls, skill executions, inputs, and output documents generated by team members.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <span className="px-3 py-1.5 rounded-xl bg-purple-950/60 border border-purple-500/30 text-purple-300 text-xs font-mono">
            Server: Online (Port 8080)
          </span>
        </div>
      </div>

      {/* Terminal View Widget */}
      <div className="rounded-3xl bg-[#090D14] border border-slate-800 overflow-hidden shadow-2xl">
        <div className="px-4 py-3 bg-[#0E1420] border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="h-3 w-3 rounded-full bg-red-500/80"></div>
            <div className="h-3 w-3 rounded-full bg-amber-500/80"></div>
            <div className="h-3 w-3 rounded-full bg-emerald-500/80"></div>
            <span className="text-xs font-mono text-slate-400 ml-2">abm-strategy-mcp-server :: stdout stream</span>
          </div>
          <span className="text-[10px] font-mono text-cyan-400">LOG_LEVEL=DEBUG</span>
        </div>

        <div className="p-4 font-mono text-xs text-slate-300 space-y-1.5 max-h-48 overflow-y-auto leading-relaxed bg-[#090D14]">
          <div className="text-slate-500">[SYSTEM] Server initialized with b2Token bearer cookie verification middleware</div>
          <div className="text-cyan-400">[INFO] Skill router active for stages 01 through 21</div>
          {logs.flatMap(l => l.logs || []).map((line, i) => (
            <div key={i} className="flex gap-2">
              <span className="text-slate-600">›</span>
              <span className={line.includes('SUCCESS') ? 'text-emerald-400' : 'text-slate-300'}>{line}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Audit Log Table / Cards */}
      <div className="space-y-4">
        <h3 className="text-base font-bold text-white flex items-center gap-2">
          <Layers className="h-5 w-5 text-cyan-400" />
          Execution Log Audit Feed
        </h3>

        <div className="space-y-3">
          {logs.map((log) => {
            const isExpanded = expandedLogId === log.id;
            return (
              <div
                key={log.id}
                className="p-5 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-4 transition"
              >
                <div
                  onClick={() => setExpandedLogId(isExpanded ? null : log.id)}
                  className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 cursor-pointer"
                >
                  <div className="flex items-center gap-3">
                    <div className="p-2.5 rounded-xl bg-purple-950/60 border border-purple-500/30 text-purple-400">
                      <Terminal className="h-4 w-4" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-bold text-white">{log.skill}</span>
                        <span className="px-2 py-0.5 text-[10px] font-mono rounded bg-emerald-950 text-emerald-300 border border-emerald-500/30">
                          {log.status}
                        </span>
                      </div>
                      <p className="text-xs text-slate-400 mt-0.5">{log.details}</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-4 text-xs font-mono text-slate-400 shrink-0">
                    <span className="flex items-center gap-1.5 text-slate-300">
                      <UserCheck className="h-3.5 w-3.5 text-indigo-400" />
                      {log.user}
                    </span>
                    <span className="text-emerald-400">{log.durationMs}ms</span>
                    {isExpanded ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
                  </div>
                </div>

                {/* Expanded Console Logs */}
                {isExpanded && (
                  <div className="pt-3 border-t border-slate-800 space-y-2">
                    <div className="text-[11px] font-mono text-slate-400">Console Trace Output:</div>
                    <div className="p-4 rounded-xl bg-black/70 border border-slate-800 font-mono text-xs text-slate-300 space-y-1">
                      {log.logs?.map((l, idx) => (
                        <div key={idx} className="text-slate-300">{l}</div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
